datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./database"
  production:
    username: ${PGUSER}
    password: ${PGPASSWORD}
    url: "postgresql://postgres:REJLBof1yeEztImIl1ID@containers-us-west-101.railway.app:7153/postgres"

ebean:
  migration:
    run: true