datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./database"
  production:
    username: ${PGUSER}
    password: ${PGPASSWORD}
    url: ${DATABASE_URL}

ebean:
  migration:
    run: true
production:
  migration:
    run: true